version: 2.1

orbs:
   win: circleci/windows@2.4.0

workflows:
  test:
    jobs:
    - build-run-windows:
        context: hello-world-demos

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: main
    jobs:
    - build-run-windows:
        context: hello-world-demos

# This CI build ensures that the demo both compiles and works correctly. For the runtime test,
# we use an SDK key and flag key that are passed in via the CircleCI project configuration;
# the flag is configured to return a true value.

jobs:
  build-run-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: insert SDK key and flag key into demo code
          command: |
            $content = Get-Content -Path .\HelloDotNet\Hello.cs
            $content = $content -Replace "SdkKey = `".*`"","SdkKey = `"$env:LD_HELLO_WORLD_SDK_KEY`""
            $content = $content -Replace "FeatureFlagKey = `".*`"","FeatureFlagKey = `"$env:LD_HELLO_WORLD_FLAG_KEY_WITH_TRUE_VALUE`""
            $content | Set-Content -Path .\HelloDotNet\Hello.cs
      - run:
          name: build demo
          command: dotnet build HelloDotNet.sln
      - run:
          name: run demo
          command: |
            dotnet run --project HelloDotNet | tee-object -variable output
